site_name: PyMapManager

theme:
  name: 'material'

#repo_url: http://github.com/cudmore/PyMapManager
repo_url: http://github.com/mapmanager/PyMapManager

edit_uri: ''

plugins:
  #- mkdocs-jupyter
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - pymapmanager
      handlers:
        python:
          selection:
            inherited_members: false
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_category_heading: true
            group_by_category: false
            heading_level: 1
            merge_init_into_class: true
            show_signature_annotations: true
            #show_object_full_path: true

nav:
    - Home: index.md
    - Web Help: web-help.md
    - Install PyMapManager: install-pymapmanager.md
    - Install Server: install-server.md
    - REST API: rest-api.md
    - Examples: 
        - a-plotting-annotations: examples/a-plotting-annotations.md
        #- b-dynamics: examples/b-dynamics.html
        #- c-intensity-analysis: examples/c-intensity-analysis.html
    - Development Notes: dev-notes.md
    - Open Source: open-source.md
    - Api:
        - baseAnnotations: api/baseAnnotations.md
        - pointAnnotations: api/pointAnnotations.md
        - lineAnnotations: api/lineAnnotations.md

#extra_css:
#    - css/extra.css
